/**
 * CLI Backend Registry - 核心注册表和通用工具函数
 * 
 * 管理所有 CLI 后端（内置 + 自定义），提供检测、注册、执行等核心功能。
 * 各 CLI 模型的配置从各自文件夹的 config.js 中加载。
 *
 * 特性：
 * - 自动检测已安装的 CLI
 * - 每个 Agent 独立的 memory 文件（不共享）
 * - 通用化配置，支持自定义 CLI
 * - 子进程输入输出监听
 * - 与现有 Agent 系统无缝集成
 */
import { existsSync, mkdirSync, writeFileSync, unlinkSync } from 'fs';
import { tmpdir } from 'os';
import path from 'path';
import { exec, spawn } from 'child_process';
import { promisify } from 'util';
import { skillRegistry } from '../skills.js';
import { knowledgeManager } from '../knowledge.js';

// 导入各 CLI 模型的配置
import { claudeCodeConfig } from './claude-code/config.js';
import { codexConfig } from './codex/config.js';
import { codebuddyConfig } from './codebuddy/config.js';

const execAsync = promisify(exec);

/**
 * CLI 后端状态
 */
export const CLIBackendState = {
  DETECTED: 'detected',       // 已检测到安装
  NOT_FOUND: 'not_found',     // 未检测到
  CONFIGURED: 'configured',   // 已配置
  ERROR: 'error',             // 检测出错
};

/**
 * 内置 CLI 后端配置列表
 * 从各文件夹的 config.js 中汇总
 */
const BUILTIN_BACKENDS = [
  claudeCodeConfig,
  codexConfig,
  codebuddyConfig,
];

/**
 * 构建 Agent 的 Memory 文件内容
 * 将 Agent 的 prompt、长期记忆、技能、知识库等合并为 markdown 格式
 * 
 * @param {object} agent - Agent 实例
 * @returns {string} markdown 格式的 memory 文件内容
 */
export function buildAgentMemoryContent(agent) {
  const lines = [];

  lines.push(`# ${agent.name} - ${agent.role}`);
  lines.push('');
  lines.push('> This file is auto-generated by AI Enterprise. Do not edit manually.');
  lines.push('');

  // 角色设定
  lines.push('## Role & Identity');
  lines.push('');
  lines.push(agent.prompt);
  lines.push('');

  // 身份信息
  lines.push('## Personal Info');
  lines.push('');
  lines.push(`- **Name**: ${agent.name}`);
  lines.push(`- **Role**: ${agent.role}`);
  lines.push(`- **Gender**: ${agent.gender === 'female' ? 'Female' : 'Male'}`);
  lines.push(`- **Age**: ${agent.age}`);
  lines.push(`- **Signature**: ${agent.signature}`);
  lines.push(`- **Skills**: ${agent.skills.join(', ')}`);
  lines.push('');

  // 性格特征
  if (agent.personality) {
    lines.push('## Personality');
    lines.push('');
    lines.push(`- **Trait**: ${agent.personality.trait}`);
    lines.push(`- **Tone**: ${agent.personality.tone}`);
    lines.push(`- **Quirk**: ${agent.personality.quirk}`);
    lines.push('');
  }

  // 长期记忆
  const longTermMemories = agent.memory.searchLongTerm();
  if (longTermMemories.length > 0) {
    lines.push('## Long-term Memories');
    lines.push('');
    const recent = longTermMemories.slice(-30);
    recent.forEach(m => {
      lines.push(`- [${m.category}] ${m.content}`);
    });
    lines.push('');
  }

  // 短期记忆
  if (agent.memory.shortTerm.length > 0) {
    lines.push('## Current Context (Short-term)');
    lines.push('');
    agent.memory.shortTerm.forEach(m => {
      lines.push(`- ${m.content}`);
    });
    lines.push('');
  }

  // 技能系统
  try {
    const agentSkills = skillRegistry.resolveAgentSkills(agent.skills);
    if (agentSkills.length > 0) {
      lines.push('## Available Skills');
      lines.push('');
      agentSkills.forEach(s => {
        lines.push(`- **${s.name}**: ${s.description}`);
        if (s.instructions) lines.push(`  - Instructions: ${s.instructions}`);
      });
      lines.push('');
    }
  } catch {}

  // 知识库
  try {
    const kbPrompt = knowledgeManager.buildKnowledgePrompt(agent.id, agent.department);
    if (kbPrompt) {
      lines.push('## Knowledge Base');
      lines.push('');
      lines.push(kbPrompt);
      lines.push('');
    }
  } catch {}

  // 团队协作规则
  lines.push('## Teamwork Rules');
  lines.push('');
  lines.push('- You are part of a team. Coordinate with colleagues when needed.');
  lines.push('- When working in parallel, avoid duplicate work and share discoveries.');
  lines.push('- Produce real, working code output. Do not just describe what you would do.');
  lines.push('- Be efficient: plan all needed operations at once, minimize tool call rounds.');
  lines.push('');

  return lines.join('\n');
}

/**
 * 获取 nvm 环境下的 shell 命令前缀
 * 用于在特定 Node 版本下执行 CLI 命令
 * 
 * @param {string|null} nodeVersion - Node 版本号，如 '20'
 * @returns {string} shell 命令前缀
 */
function getNvmPrefix(nodeVersion) {
  if (!nodeVersion) return '';
  return `export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm use ${nodeVersion} > /dev/null 2>&1 && `;
}

/**
 * CLI Backend Registry - 管理所有 CLI 后端
 */
export class CLIBackendRegistry {
  constructor() {
    /** @type {Map<string, {config: object, state: string, version: string|null, lastDetected: Date|null}>} */
    this.backends = new Map();

    // 注册内置后端
    BUILTIN_BACKENDS.forEach(config => {
      this.backends.set(config.id, {
        config: { ...config },
        state: CLIBackendState.NOT_FOUND,
        version: null,
        lastDetected: null,
      });
    });
  }

  /**
   * 注册自定义 CLI 后端
   * @param {object} config - CLI 配置
   */
  register(config) {
    if (!config.id || !config.execCommand) {
      throw new Error('CLI backend config requires at least id and execCommand');
    }
    const fullConfig = {
      id: config.id,
      name: config.name || config.id,
      description: config.description || '',
      icon: config.icon || '🔧',
      detectCommand: config.detectCommand || `${config.execCommand} --version`,
      execCommand: config.execCommand,
      execArgs: config.execArgs || ['-p', '{prompt}'],
      interactiveArgs: config.interactiveArgs || [],
      memoryDir: config.memoryDir || `.${config.id}`,
      memoryFile: config.memoryFile || 'MEMORY.md',
      memoryFormat: config.memoryFormat || 'markdown',
      workingDirSupport: config.workingDirSupport !== false,
      pipeMode: config.pipeMode || 'args',
      outputMode: config.outputMode || 'stdout',
      initCommand: config.initCommand || null,
      customEnv: config.customEnv || {},
      nvmNode: config.nvmNode || null,
      builtin: false,
    };

    this.backends.set(fullConfig.id, {
      config: fullConfig,
      state: CLIBackendState.NOT_FOUND,
      version: null,
      lastDetected: null,
    });

    console.log(`🔧 CLI Backend registered: ${fullConfig.name} (${fullConfig.id})`);
    return fullConfig;
  }

  /**
   * 移除自定义 CLI 后端
   */
  unregister(backendId) {
    const backend = this.backends.get(backendId);
    if (!backend) return false;
    if (backend.config.builtin) {
      throw new Error('Cannot unregister built-in CLI backends');
    }
    this.backends.delete(backendId);
    return true;
  }

  /**
   * 检测单个 CLI 是否已安装
   * @param {string} backendId
   * @returns {Promise<{detected: boolean, version: string|null}>}
   */
  async detect(backendId) {
    const backend = this.backends.get(backendId);
    if (!backend) throw new Error(`CLI backend not found: ${backendId}`);

    const { config } = backend;
    const nvmPrefix = getNvmPrefix(config.nvmNode);
    const detectCmd = nvmPrefix + config.detectCommand;

    try {
      const { stdout } = await execAsync(detectCmd, {
        timeout: 10000,
        shell: '/bin/bash',
        env: { ...process.env, ...config.customEnv },
      });
      const version = stdout.trim().split('\n')[0];
      backend.state = CLIBackendState.DETECTED;
      backend.version = version;
      backend.lastDetected = new Date();
      console.log(`✅ CLI detected: ${config.name} (${version})`);
      return { detected: true, version };
    } catch (error) {
      backend.state = CLIBackendState.NOT_FOUND;
      backend.version = null;
      backend.lastDetected = new Date();
      return { detected: false, version: null };
    }
  }

  /**
   * 检测所有已注册的 CLI
   * @returns {Promise<object[]>} 检测结果列表
   */
  async detectAll() {
    const results = [];
    const promises = [...this.backends.keys()].map(async (id) => {
      const result = await this.detect(id);
      results.push({ id, ...result, name: this.backends.get(id).config.name });
    });
    await Promise.all(promises);
    return results;
  }

  /**
   * 获取所有可用（已检测到）的后端
   */
  getAvailableBackends() {
    return [...this.backends.values()]
      .filter(b => b.state === CLIBackendState.DETECTED || b.state === CLIBackendState.CONFIGURED)
      .map(b => ({
        id: b.config.id,
        name: b.config.name,
        description: b.config.description,
        icon: b.config.icon,
        version: b.version,
        builtin: b.config.builtin,
        state: b.state,
      }));
  }

  /**
   * 列出所有后端及其状态
   */
  listAll() {
    return [...this.backends.values()].map(b => ({
      id: b.config.id,
      name: b.config.name,
      description: b.config.description,
      icon: b.config.icon,
      rating: b.config.rating || 80,
      version: b.version,
      state: b.state,
      builtin: b.config.builtin,
      lastDetected: b.lastDetected,
      nvmNode: b.config.nvmNode,
      execCommand: b.config.execCommand,
    }));
  }

  /**
   * 为 Agent 写入 memory 文件
   * 在 Agent 的工作目录下创建 CLI 对应的 memory 文件
   * 
   * @param {string} backendId - CLI 后端 ID
   * @param {object} agent - Agent 实例
   * @param {string} workspaceDir - Agent 的工作空间目录
   */
  writeAgentMemory(backendId, agent, workspaceDir) {
    const backend = this.backends.get(backendId);
    if (!backend) throw new Error(`CLI backend not found: ${backendId}`);

    const { config } = backend;
    const memoryContent = buildAgentMemoryContent(agent);

    const agentDir = path.join(workspaceDir, `_cli_${agent.id.slice(0, 8)}`);
    const memDir = path.join(agentDir, config.memoryDir);

    if (!existsSync(memDir)) {
      mkdirSync(memDir, { recursive: true });
    }

    const memFilePath = path.join(memDir, config.memoryFile);
    writeFileSync(memFilePath, memoryContent, 'utf-8');

    console.log(`📝 CLI memory written: ${config.name} -> ${memFilePath}`);
    return { agentDir, memFilePath };
  }

  /**
   * 通过 CLI 执行任务
   * 核心方法：将 Agent 的任务通过 CLI 子进程执行
   * 
   * @param {string} backendId - CLI 后端 ID
   * @param {object} agent - Agent 实例
   * @param {object} task - 任务描述 { title, description, context, requirements }
   * @param {string} workspaceDir - 工作空间目录
   * @param {object} callbacks - 回调 { onOutput, onError, onComplete }
   * @param {object} options - 可选参数 { timeout }
   * @returns {Promise<{output: string, exitCode: number, duration: number}>}
   */
  async executeTask(backendId, agent, task, workspaceDir, callbacks = {}, options = {}) {
    const backend = this.backends.get(backendId);
    if (!backend) throw new Error(`CLI backend not found: ${backendId}`);
    if (backend.state !== CLIBackendState.DETECTED && backend.state !== CLIBackendState.CONFIGURED) {
      throw new Error(`CLI backend ${backendId} is not available (state: ${backend.state})`);
    }

    const { config } = backend;

    // 1. 写入 memory 文件
    const { agentDir } = this.writeAgentMemory(backendId, agent, workspaceDir);

    // 2. 构建 prompt
    const prompt = this._buildTaskPrompt(task);

    // 3. 构建命令行参数
    // Strategy: always use stdin for prompt delivery when running via nvm/bash -c
    // because shell escaping of large multi-line prompts is unreliable.
    // For non-nvm (direct spawn), args are safe since spawn doesn't go through shell.
    const hasPromptPlaceholder = config.execArgs.some(arg => arg.includes('{prompt}'));
    const isNvmMode = !!config.nvmNode;
    // In nvm mode: strip {prompt} from args, deliver via stdin (temp file piped in)
    // In non-nvm mode: replace {prompt} directly in args (spawn doesn't use shell)
    const useStdin = !hasPromptPlaceholder || isNvmMode;
    const args = isNvmMode
      ? config.execArgs.filter(arg => arg !== '{prompt}').map(arg => arg.replace('{prompt}', ''))
      : config.execArgs.map(arg => arg.replace('{prompt}', prompt));

    // 4. 构建执行环境（每个 agent 独立的 XDG 目录，避免 CLI 记忆共享）
    const agentConfigDir = path.join(agentDir, '.config');
    const agentDataDir = path.join(agentDir, '.local', 'share');
    const agentStateDir = path.join(agentDir, '.local', 'state');
    const agentCacheDir = path.join(agentDir, '.cache');
    // 确保隔离目录存在
    for (const dir of [agentConfigDir, agentDataDir, agentStateDir, agentCacheDir]) {
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    }
    const env = {
      ...process.env,
      ...config.customEnv,
      // 通过 XDG 环境变量隔离 CLI 工具的配置/记忆/状态/缓存目录
      // 这样 CodeBuddy/Claude Code 等 CLI 会将 memories、sessions 等存在 agent 自己的目录下
      XDG_CONFIG_HOME: agentConfigDir,
      XDG_DATA_HOME: agentDataDir,
      XDG_STATE_HOME: agentStateDir,
      XDG_CACHE_HOME: agentCacheDir,
    };
    const cwd = config.workingDirSupport ? agentDir : workspaceDir;

    // 5. 确保工作目录存在
    if (!existsSync(cwd)) {
      mkdirSync(cwd, { recursive: true });
    }

    const timeoutMs = options.timeout || 600000; // 10 minutes max total timeout
    const inactivityTimeoutMs = options.inactivityTimeout || 120000; // 2 minutes no-output timeout

    const promptMode = useStdin ? 'stdin' : 'args';
    console.log(`🚀 CLI executing: ${config.execCommand} (${promptMode} prompt, ${Math.round(timeoutMs/1000)}s timeout, ${Math.round(inactivityTimeoutMs/1000)}s inactivity limit)`);
    console.log(`   Working dir: ${cwd}`);
    console.log(`   Prompt length: ${prompt.length} chars, mode: ${promptMode}`);

    const startTime = Date.now();

    return new Promise((resolve, reject) => {
      let output = '';
      let errorOutput = '';
      let lastActivityTime = Date.now();
      let totalTimer = null;
      let inactivityTimer = null;
      let killed = false;

      const killChild = (reason) => {
        if (killed) return;
        killed = true;
        const elapsed = Date.now() - startTime;
        console.warn(`⏰ CLI killed: ${config.name} — ${reason} (after ${Math.round(elapsed/1000)}s)`);
        try { child.kill('SIGTERM'); } catch {}
        // Force kill after 5 seconds if SIGTERM doesn't work
        setTimeout(() => {
          try { child.kill('SIGKILL'); } catch {}
        }, 5000);
      };

      const resetInactivityTimer = () => {
        lastActivityTime = Date.now();
        if (inactivityTimer) clearTimeout(inactivityTimer);
        inactivityTimer = setTimeout(() => {
          killChild(`no output for ${Math.round(inactivityTimeoutMs/1000)}s`);
        }, inactivityTimeoutMs);
      };

      let child;
      const nvmPrefix = getNvmPrefix(config.nvmNode);

      // Write prompt to temp file for stdin delivery (avoids shell escaping issues)
      let promptTmpFile = null;
      if (useStdin && isNvmMode) {
        promptTmpFile = path.join(tmpdir(), `ai-ent-prompt-${Date.now()}-${Math.random().toString(36).slice(2)}.txt`);
        writeFileSync(promptTmpFile, prompt, 'utf-8');
      }

      if (nvmPrefix) {
        // Build shell command with args (prompt NOT in args for nvm mode)
        const argsStr = args.filter(a => a.length > 0).map(a => `'${a.replace(/'/g, "'\\''")}'`).join(' ');
        // Pipe prompt via stdin from temp file
        const stdinPipe = promptTmpFile ? `cat '${promptTmpFile}' | ` : '';
        const fullCommand = `${nvmPrefix}${stdinPipe}${config.execCommand} ${argsStr}`;
        child = spawn('bash', ['-c', fullCommand], {
          cwd,
          env,
          stdio: ['pipe', 'pipe', 'pipe'],
        });
      } else {
        child = spawn(config.execCommand, args, {
          cwd,
          env,
          stdio: ['pipe', 'pipe', 'pipe'],
        });
      }

      // Total timeout: hard kill after timeoutMs
      totalTimer = setTimeout(() => {
        killChild(`total timeout ${Math.round(timeoutMs/1000)}s reached`);
      }, timeoutMs);

      // Start inactivity timer
      resetInactivityTimer();

      // 通过 stdin 管道传入 prompt（非 nvm 模式且 useStdin 时）
      // nvm 模式的 stdin 已通过 temp file + cat 管道传入
      if (useStdin && !isNvmMode) {
        child.stdin.write(prompt);
      }
      child.stdin.end();

      child.stdout.on('data', (data) => {
        const chunk = data.toString();
        output += chunk;
        resetInactivityTimer(); // Reset inactivity timer on output
        if (callbacks.onOutput) {
          try { callbacks.onOutput(chunk); } catch {}
        }
      });

      child.stderr.on('data', (data) => {
        const chunk = data.toString();
        errorOutput += chunk;
        resetInactivityTimer(); // stderr also counts as activity
        if (callbacks.onError) {
          try { callbacks.onError(chunk); } catch {}
        }
      });

      child.on('close', (code) => {
        // Clean up timers and temp files
        if (totalTimer) clearTimeout(totalTimer);
        if (inactivityTimer) clearTimeout(inactivityTimer);
        if (promptTmpFile) { try { unlinkSync(promptTmpFile); } catch {} }

        const duration = Date.now() - startTime;
        const result = {
          output: output.trim(),
          errorOutput: errorOutput.trim(),
          exitCode: killed ? (code ?? -1) : code,
          duration,
          backendId: config.id,
          backendName: config.name,
          killed,
        };

        console.log(`✅ CLI completed: ${config.name}, exit code ${code}${killed ? ' (killed)' : ''}, ${duration}ms`);

        if (callbacks.onComplete) {
          try { callbacks.onComplete(result); } catch {}
        }

        resolve(result);
      });

      child.on('error', (error) => {
        // Clean up timers and temp files
        if (totalTimer) clearTimeout(totalTimer);
        if (inactivityTimer) clearTimeout(inactivityTimer);
        if (promptTmpFile) { try { unlinkSync(promptTmpFile); } catch {} }

        const duration = Date.now() - startTime;
        console.error(`❌ CLI error: ${config.name} - ${error.message}`);
        reject({
          output: output.trim(),
          errorOutput: error.message,
          exitCode: -1,
          duration,
          backendId: config.id,
          backendName: config.name,
          error: error.message,
          killed,
        });
      });
    });
  }

  /**
   * 构建任务 prompt（传给 CLI 的完整指令）
   */
  _buildTaskPrompt(task) {
    let prompt = `Please complete the following task:\n\n`;
    prompt += `**Task**: ${task.title}\n`;
    if (task.description) {
      prompt += `**Description**: ${task.description}\n`;
    }
    if (task.context) {
      prompt += `\n**Context**:\n${task.context}\n`;
    }
    if (task.requirements) {
      prompt += `\n**Requirements**:\n${task.requirements}\n`;
    }
    prompt += `\nPlease complete the task diligently. Produce real, working output. Be efficient and give a final summary after completing the work.`;
    return prompt;
  }

  /**
   * 序列化（持久化用）
   */
  serialize() {
    const customBackends = [];
    for (const [id, backend] of this.backends) {
      if (!backend.config.builtin) {
        customBackends.push(backend.config);
      }
    }
    return {
      customBackends,
      savedAt: new Date().toISOString(),
    };
  }

  /**
   * 从序列化数据恢复自定义后端
   */
  restore(data) {
    if (!data || !data.customBackends) return;
    for (const config of data.customBackends) {
      try {
        this.register(config);
      } catch (e) {
        console.error(`[CLIBackendRegistry] Failed to restore backend "${config.id}":`, e.message);
      }
    }
  }
}

// 全局单例
export const cliBackendRegistry = new CLIBackendRegistry();
